### ISSUE TITLE
Divider.java changes the bounds of a Drawable that has not been mutate()d.

### ISSUE THREAD

**Issue by emmano** [Karumi/Dividers#9]
From the docs: 

> By default, all drawables instances loaded from the same resource share a common state; if you modify the state of one instance, all the other instances will receive the same modification.

Calling `Drawable#mutate()` before manipulating the `Drawable` could be a solution.

**Comment by Serchinastico** [comment]
Good catch, I'll try to find a solution (probably based in ```mutate()```) as soon as I can. PRs are welcome as well :)

**Comment by emmano** [comment]
I could send a PR later today (late tonight your time). I think it should be as simple as calling mutate() before manipulating the Drawable, probably before calling setBounds().

**Comment by Serchinastico** [comment]
Issue solved by @emmano
